// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptdjtgonyxilanijzugt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0ZGp0Z29ueXhpbGFuaWp6dWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNTM1MjMsImV4cCI6MjA1OTcyOTUyM30.0dJbiQfJ5OLGGf6FEzrm0FSvwjQIxkiCddvrqakJxlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);